spring.application.name=proj

spring.datasource.url=jdbc:mysql://mysql-ada-ada-proj.b.aivencloud.com:10661/defaultdb?sslMode=PREFERRED&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.hikari.data-source-properties.sslCa=classpath:certs/ca.pem
spring.datasource.hikari.data-source-properties.enabledTLSProtocols=TLSv1.2,TLSv1.3
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_2ACT7lxuIZE234iwYQz
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.data-source-properties.useUnicode=true
spring.datasource.hikari.data-source-properties.characterEncoding=utf8


spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul
spring.jackson.time-zone=Asia/Seoul

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=55000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.connection-test-query=SELECT 1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080
server.forward-headers-strategy=framework

app.auto-increment.maintain.enabled=true
app.auto-increment.maintain.tables=users,posts,comments,comments_likes,refresh_token,user_data,post_likes,points_usage_history
server.address=0.0.0.0

spring.devtools.restart.enabled=false
spring.devtools.add-properties=false
spring.output.ansi.enabled=always

jwt.secret=hCB8xQ7mVYF2wzG3JpA9kL5rN2uS8eD1tQ6yZ3mB7cP4vX9sR1aT6uW3qE8nK5bM
jwt.access-expiration-ms=900000
jwt.refresh-expiration-ms=604800000

app.auto-increment.maintain.resequence-order=false
app.auto-increment.maintain.order-column=order_no

app.auto-increment.maintain.resequence-primary.enabled=true
app.auto-increment.maintain.resequence-primary.tables=refresh_token,post,post_likes,comments,comments_likes,user_ban,user_report

spring.servlet.multipart.max-file-size=450MB
spring.servlet.multipart.max-request-size=450MB

spring.web.locale=ko_KR
spring.web.locale-resolver=fixed
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
logging.charset.console=UTF-8
logging.charset.file=UTF-8

server.tomcat.max-http-form-post-size=500MB
server.tomcat.max-swallow-size=500MB

spring.servlet.multipart.file-size-threshold=10MB
spring.servlet.multipart.location=uploads/tmp