app:
  cookie:
    http-only: true
    secure: ${COOKIE_SECURE:true}
    same-site: None
    max-age: 604800

spring:
  jpa:
    hibernate:
      ddl-auto: validate

server:
  forward-headers-strategy: framework
