app.storage.mode=s3
app.storage.s3.bucket=gbsw-s3

# app.storage.s3.region=ap-northeast-2

# app.storage.s3.key-prefix=proj
# app.storage.s3.endpoint=http://localhost:9000
# app.storage.s3.path-style-access=true
